feature: added ability to prefix utility classes and variables
hankchizljaw/gorko pull request #26
Opened 2021-10-20 14:08 UTC by bytelabsco

Also added documentation to readme.md

2021-10-20 14:26 UTC, bytelabsco commented
closes #25

2021-10-20 14:39 UTC, Andy-set-studio commented
This is looking great! I'm right in a crunch on client work so want to give this a proper review when I'm done (hopefully early november), to give it the right justice it deserves. 

I'll leave some passing comments now, but thank you so much for this. It's a really good start!!

2021-10-20 14:40 UTC, andy-piccalilli commented on src/_default-config.scss
> +  ),
Once concern I have here is that we need to support people updating Gorko and not being aware of this feature. Is there an accommodation for this config section not existing?

2021-10-20 14:41 UTC, Andy-set-studio commented on src/generator/workers/_get-namespace.scss
> +    );
Ah this answers my above comment about what happens when the config doesn't exist!

2021-11-09 22:26 UTC, bytelabsco commented
Just wanted to touch base and see if there's anything I can do to help.

2021-11-10 10:36 UTC, andy-piccalilli commented
Ah sorry, @bytelabsco. I'll review it now :)

2021-11-10 10:40 UTC, andy-piccalilli requested changes
This all looks great so far. I'll just give it a test drive locally.

One thing that would be great is instead of `vars`, we set that property to be `css-vars`, so it is consistent the the custom properties setup.

Really nice work though, @bytelabsco. Thank you so much

2021-11-10 10:40 UTC, andy-piccalilli commented on readme.md
> +Gorko supports 'namespacing' both the generated class and variable names by allowing you to specify a prefix.  This is done using the `namespace` map within `$gorko-config`.  The default `namespace`
```suggestion
Gorko supports “namespacing” both the generated class and variable names by allowing you to specify a prefix.  This is done using the `namespace` map within `$gorko-config`.  The default `namespace` config looks like this:
```

Just a little nit here

2021-11-10 10:40 UTC, andy-piccalilli commented on readme.md
> +Specifying a value for `prefix` will append that value to classes (by default) and css variables (opt-in).  You are responsible for appending any separating character, such as a dash or underscore.
```suggestion
Specifying a value for `prefix` will append that value to classes (by default) and css variables (opt-in).  You are responsible for appending any separating character, such as a dash or underscore. For example, if your namespace is `my-app-`, you need to add the trailing `-` character in the `'prefix'` section.
```

2021-11-10 10:51 UTC, andy-piccalilli commented
Test drive was a great success. Really cool feature you've added here :)

2021-11-10 15:50 UTC, bytelabsco commented
I went ahead and changed the 'vars' property to 'css-vars' to match the other configuration sections.

2021-11-10 16:41 UTC, andy-piccalilli commented
Awesome, thank you. Let's get this merged!

2021-11-10 16:41 UTC, andy-piccalilli approved these changes

2021-11-10 16:41 UTC, merged

2021-11-10 16:44 UTC, andy-piccalilli commented
Also, are you on Twitter so I can credit you with this release?

2021-11-10 20:28 UTC, motionsuggests commented
This is super cool. Great work @bytelabsco !